name = "contact-bot"
main = "src/index.js"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "msgs", id = "fill_id_here" },
  { binding = "users", id = "fill_id_here" }
]
